spring:
  application:
    name: user
  datasource:
    hikari:
      data-source-name: user
    url: jdbc:mysql://localhost:3306/mvc
    username: root
    password: Krishnani@7634
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: user
    description: User Service
    version: 1.0.0
