spring:
  application:
    name: user
  datasource:
    hikari:
      data-source-name: user
    url: jdbc:mysql://localhost:3306/mvc
    username: root
    password: Krishnani@7634
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


      

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: user
    description: User Service
    version: 1.0.0
